[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.build]
cmds = ["python -m compileall ."]

[start]
cmd = "./start.sh"
