[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.build]
cmds = ["python -m compileall ."]

[start]
cmd = "python run.py --port $PORT --host 0.0.0.0"
